require 'pry'
require 'active_record'
require_relative 'db_config'
require_relative 'models/user'
require_relative 'models/user_type'
require_relative 'models/game'
require_relative 'models/reservation'
